Issue/4 settings page
mkdo/link-picker-for-cmb2 pull request #11
Opened 2017-12-06 16:44 UTC by m9n

- Improved the documentation (removed reference to settings page which isn't necessary, added usage examples).
- Now autoloading classes, just in case we expand to add a settings page in future.

2017-12-07 22:12 UTC, mattwatsoncodes requested changes

2017-12-07 22:12 UTC, mwtsn commented on README.md
> +if ( 'true' == $url[0]['blank'] ) {
We need === here `( 'true' === $url[0]['blank'] )`.

2017-12-07 22:12 UTC, mwtsn commented on README.md
> +$url = get_post_meta( $post_ID, '_yourprefix_url', true );
get_the_ID() is more performant than $post_ID.

2017-12-07 22:12 UTC, mwtsn commented on README.md
> +	esc_attr( $url[0]['text'] )
The text parameter isn't an attribute, so use `esc_html` here.

2017-12-07 22:12 UTC, mwtsn commented on readme.txt
> +4. There are no settings for the plugin.  See examples below for usage.
Same deal as the code examples in the other readme here :)

2017-12-07 22:12 UTC, mwtsn commented on README.md
> +printf(
For clarity of code, I always prefer to use %1s, %2s etc.. in a printf, however most of the time I will break out of the php and use:

```
?>
<a href=""...
<?php
```

I just find this easier to read. But that is my preference and not wrong at all.

2017-12-07 22:12 UTC, mwtsn commented on plugin.php
> +foreach ( glob( plugin_dir_path( __FILE__ ) . 'php/class-*.php' ) as $filename ) {
Good thinking 👍. I'd also like to move the functions out of the main controller into the main plugin file, but this can wait for another day.

2017-12-18 09:05 UTC, m9n commented
I believe I've responded to all your issues here, @mwtsn. Let me know if there's anything else I can do?

2017-12-20 10:59 UTC, merged